### ISSUE TITLE
Seemingly unnecessary case analysis

### ISSUE THREAD

**Issue by mrkkrp** [kosmikus/SSGEP#3]
In the lecture notes "Applying type-level and generic programming in Haskell", on page 34, section 2.5.1, we have this definition:

```haskell
gdefNS :: forall xs xss . (SListI xs, All Default xs) => NS (NP I) (xs ': xss)
gdefNS = case sList :: SList xs of
  SCons -> Z (hcpure (Proxy :: Proxy Default) (I def))
```

I don't understand why you perform case analysis here. `sList :: SList xs` shows whether there are any types in N-ary product, but:

1. You impose non-empty length on the collection of sum components, but not on first product. Thus the code misses a case for `SNil`.
2. Touching length of product seems completely unnecessary here, it's all handled by `hcpure` anyway.

So this code I think should be:

```haskell
gdefNS :: forall xs xss. (SListI xs, All Default xs) => NS (NP I) (xs ': xss)
gdefNS = Z (hcpure (Proxy :: Proxy Default) (I def))
```

P.S. Nice reading, I'll try `generics-sop` next time I need generics.

**Comment by kosmikus** [comment]
Yes, you're right. I'll fix it.

**Comment by kosmikus** [comment]
Done. Well spotted, thanks a lot!
